-- *****************************************************************************
-- This script contains INSERT statements for populating tables with seed data
-- *****************************************************************************

BEGIN TRAN;

INSERT INTO landmark VALUES ('TownHall', '1909 W 25th St, Cleveland, OH 44113', '216.344.9400', 'Locally sourced & innovative bar bites & vegan options served in a contemporary setting with patio.', null, 4.3, 2, null, 'townhallohiocity.com');
INSERT INTO landmark VALUES ('Barrio', '503 Prospect Ave E, Cleveland, OH 44115', '216.862.4652', 'Local chain serving signature & build-your-own tacos, plus cocktails, in a hip, casual space.', null, 4.4, 1, null, 'barrio-tacos.com');
INSERT INTO landmark VALUES ('Tilted Kilt Pub and Eatery', '21 Prospect Ave E, Cleveland, OH 44115', '216.771.5458', 'UK-inspired pub chain with kilt-clad waitresses serving fish 'n' chips & bar food.', null, 4.2, 2, null, 'tiltedkilt.com');
INSERT INTO landmark VALUES ('Shooters On the Water', '1148 Main Ave, Cleveland, OH 44113', '216.861.6900', 'A high-volume venue offering a long menu of familiar fare & a patio showing a sound & light show.', null, 4.5, 2, null, 'shootersflats.com');
INSERT INTO landmark VALUES ('Hofbräuhaus', '1550 Chester Ave, Cleveland, OH 44115', '216.621.2337', 'German microbrewery with an on-site restaurant & beer garden offering traditional eats & live music.', null, 4.5, 3, null, 'hofbrauhauscleveland.com');
INSERT INTO landmark VALUES ('TOMO Sushi & Hibachi Restaurant', '1293 W 9th St, Cleveland, OH 44113', '216.696.4444', 'Huge 4-floor venue offering Japanese hibachi fare & sushi plus lounges with DJs, music & dancing.', null, 3.5, 3, null, 'tomohibachiandsushi.com');
INSERT INTO landmark VALUES ('Brasa Grill Brazilian Steakhouse', '1300 W 9th St, Cleveland, OH 44113', '216.575.0699', 'Lively Brazilian churrascaria with all-you-can-eat carved meats served by gauchos plus a full bar.', null, 3.5, 3, null, 'brasagrillsteakhouse.com');
INSERT INTO landmark VALUES ('Thirsty Parrot', '812 Huron Rd E, Cleveland, OH 44115', '216.685.3200', 'Relaxed cantina near Progressive Field, offering pub fare with pre- and post-game specials.', null, 3.5, 2, null, 'thirstyparrot.com');
INSERT INTO landmark VALUES ('Morton''s The Steakhouse', '1600 W 2nd St, Cleveland, OH 44113', '216.621.6200', 'Upscale chain for aged prime beef, seafood & other traditional steakhouse fare in a clubby space.', null, 4.6, 4, null, 'mortons.com/cleveland');
INSERT INTO landmark VALUES ('Cibréo Italian Kitchen', '1438 Euclid Ave, Cleveland, OH 44115', '216.862.9212', 'Elevated Italian dishes & cocktails offered in a candlelit space with stone walls & brick archways.', null, 4.1, 4, null, 'http://thedriftwoodgroup.com/restaurants/cibreo-italian-kitchen/');
INSERT INTO landmark VALUES ('Blue Point Grille', '700 W St Clair Ave, Cleveland, OH 44113', '216.875.7827', 'Bustling institution serving upscale seafood in an elegant, multilevel setting with skyline views.', null, 4.6, 3, null, 'bluepointgrille.com');
INSERT INTO landmark VALUES ('Merwin''s Wharf', '1785 Merwin Ave, Cleveland, OH 44113', '216.664.5696', 'Relaxed riverfront bar & grill offering Southern-leaning comfort food, outdoor tables & live music.', null, 3.9, 3, null, 'https://clevelandmetroparks.com/parks/visit/parks/lakefront-reservation/merwin-s-wharf');
INSERT INTO landmark VALUES ('Mabel''s BBQ', '2050 E 4th St, Cleveland, OH 44115', '216.417.8823', 'Cool, bi-level, industrial-chic BBQ spot with communal tables & a long bar with many bourbons.', null, 4.0, 2, null, 'mabelsbbq.com');
INSERT INTO landmark VALUES ('Market Garden Brewery', '1947 W 25th St, Cleveland, OH 44113', '216.621.4000', 'American gastropub with a patio, house beers, a distillery & a menu of creative sandwiches & tacos.', null, 4.0, 2, null, 'marketgardenbrewery.com');
INSERT INTO landmark VALUES ('The Bourbon Street Barrel Room', '2393 Professor Ave, Cleveland, OH 44113', '216.298.4400', 'Vibrant restaurant with New Orleans–inspired decor & cuisine, plus 2 bars & rotating craft brews.', null, 4.4, 3, null, 'bourbonstreetbarrelroom.com');
INSERT INTO landmark VALUES ('Dante', '2247 Professor Ave Suite C, Cleveland, OH 44113', '216.274.1200', 'Modern, Mediterranean-tinged New American dining & late-night noodles in a former bank building.', null, 4.6, 3, null, 'dantetremont.com');
INSERT INTO landmark VALUES ('Hyde Park Prime Steakhouse', '123 W Prospect Ave, Cleveland, OH 44115', '216.344.2444', 'High-end steakhouse chain serving grilled meats, seafood & cocktails in a sophisticated setting.', null, 4.1, 3, null, 'hydeparkrestaurants.com');
INSERT INTO landmark VALUES ('Michaelangelo''s', '2198 Murray Hill Rd, Cleveland, OH 44106', '216.721.0300', 'Upscale Piedmontese cuisine is served in an elegant carriage house with a fireplace & wine bar.', null, 4.5, 3, null, 'mangelos.com');
INSERT INTO landmark VALUES ('Flannery''s Pub', '323 Prospect Ave E, Cleveland, OH 44115', '216.781.7782', 'Irish-American watering hole with hearty comfort food, Imperial pints & live entertainment.', null, 4.1, 2, null, 'flannerys.com');
INSERT INTO landmark VALUES ('Wahlburgers', '2105 Ontario St, Cleveland, OH 44115', '216.302.1001', 'There is no better feeling than sitting at the table together, sharing good food, a few laughs and lots of love. At Wahlburgers we share a bit of that feeling every day with every guest. Our hospitality comes from the heart.', null, 3.6, 2, null, 'wahlburgersrestaurant.com');
INSERT INTO landmark VALUES ('Lago East Bank', '1091 W 10th St, Cleveland, OH 44113', '216.862.8065', 'Late-night Aloft Hotel outpost offering upscale Italian dishes & cocktails with Lake Erie views.', null, 4.2, 2, null, 'lagoeastbank.com');
INSERT INTO landmark VALUES ('Pickwick & Frolic', '2035 E 4th St, Cleveland, OH 44115', '216.241.7425', 'Prime rib & pasta are on offer at this spot staging comedy shows, burlesque acts & dinner theater.', null, 4.2, 2, null, 'pickwickandfrolic.com');


COMMIT;