var quotes = [
	'You\'re mine.  Mine, as I\'m yours.  And if we die, we die.  All men must die, Jon Snow.  But first, we\'ll live. - Ygritte',
	'When you play the game of thrones, you win or you die.  There is no middle ground. - Cersei Lannister',
	'Rhaegar fought valiantly, Rhaegar fought nobly, and Rhaegar died. - Jorah Mormont',
	'There is only one god, and his name is Death.  And there is only one thing we say to Death: not today. - Syrio Forel',
	'You will never walk again... but you will fly. - Bloodraven',
	'Edd, fetch me a block. - Jon Snow',
	'Night gathers, and now my watch begins.  It shall not end until my death.  I shall take no wife, hold no lands, father no children.  I shall wear no crowns and win no glory.  I shall live and die at my post.  I am the sword in the darkness.  I am the watcher on the walls.  I am the fire that burns against the cold, the light that brings the dawn, the horn that wakes the sleepers, the shield that guards the realms of men.  I pledge my life and honor to the Night\'s Watch, for this night and all the nights to come. - Vow of the Night\'s Watch',
	'A mind needs books as a sword needs a whetstone, if it is to keep its edge. - Tyrion Lannister',
	'You know nothing, Jon Snow. - Ygritte',
	'Power resides where men believe it resides... It\'s a trick, a shadow on the wall. - Varys',
	'When the snows fall and the white winds blow, the lone wolf dies, but the pack survives. - Eddard Stark',
	'Never forget what you are, for surely the world will not.  Make it your strength.  Then it can never be your weakness.  Armor yourself in it, and it will never be used to hurt you. - Tyrion Lannister',
	'Summer will end soon enough, and childhood as well. - Eddard Stark',
	'What is dead may never die, but rises again, harder and stronger - Words of the Drowned God',
	'For the night is dark and full of terrors. - Words of R\'hllor',
	'So I will only ask you once, Lord Snow.  Are you a brother of the Night\'s Watch, or a bastard boy who wants to play at war? - Jeor Mormont',
	'I\'m honest.  It\'s the world that\'s awful. - Sandor Clegane',
	'The common people pray for rain, healthy children, and a summer that never ends.  It is no matter to them if the high lords play their game of thrones, so long as they are left in peace.  They never are. - Jorah Mormont',
	'The man who passes the sentence should swing the sword.  If you would take a man\'s life, you owe it to him to look into his eyes and hear his final words.  And if you cannot bear to do that, then perhaps the man does not deserve to die. - Eddard Stark',
	'Summer friends will melt away like summer snows, but winter friends are friends forever. - Mully',
	'I have a tender spot in my heart for cripples, bastards, and broken things. - Tyrion Lannister',
	'There is a savage beast in every man, and it stirs when you put a sword in his hand. - Jorah Mormont',
	'Only a fool humbles himself when the world is so full of men eager to do that job for him. - Theon Greyjoy',
	'You want to know the horrible truth?  I can\'t even remember what she looked like.  I only know she was the one thing I ever wanted, and seven kingdoms couldn\'t fill the hole she left behind. - Robert Baratheon',
	'He would see this country burn if he could be king of the ashes. - Varys',
	'Gods help you, Theon Greyjoy.  Now you are truly lost. - Rodrik Cassel',
	'We were king\'s men, knights, and heroes... but some knights are dark and full of terror, my lady.  War makes monsters of us all. - Thoros of Myr',
	'I will go to my grave thinking of my brother\'s peach. - Stannis Baratheon',
	'When the sun has set, no candle can replace it. - Loras Tyrell',
	'A reader lives a thousand lives before he dies.  The man who never reads lives only one. - Jojen Reed',
	'Because they are the knights of summer, and winter is coming. - Catelyn Stark',
	'So young.  Though mayhaps this was a blessing.  Had he lived, he would have grown up to be a Frey. - Wyman Manderly',
	'Fear cuts deeper than swords. - Syrio Forel',
	'I just want to stand on top of the Wall and piss off the edge of the world. - Tyrion Lannister',
	'I think mothers and fathers made up the gods because they wanted their children to sleep through the night. - Davos Seaworth',
	'The storms come and go, waves crash overhead, the big fish eat the little fish, and I keep on paddling. - Varys',
	'Kill the boy, Jon Snow.  Winter is almost upon us.  Kill the boy and let the man be born. - Aemon Targaryen',
	'You poor stupid blind crippled fool.  Must I spell out every little thing for you?  Very well.  Cersei is a lying whore, she\'s been fucking Lancel and Osmund  Kettleblack and probably Moon Boy for all I know.  And I am the monster they all say I am.  Yes, I killed your vile son. - Tyrion Lannister',
	'There must always be a Stark in Winterfell. - Catelyn Stark',
	'Why is it always the innocents who suffer most, when you high lords play your game of thrones? - Varys',
	'I understand that if any more words come pouring out of your cunt mouth I\'m going to have to eat every fucking chicken in this room. - Sandor Clegane',
	'Godless?  Why, Aeron, I am the godliest man ever to raise sail!  You serve one god, Damphair, but I have served ten thousand.  From Ib to Asshai, when men see my sails, they pray. - Euron Greyjoy',
	'The most beautiful woman in the world has urgent need of my axe. - Victarion Greyjoy.',
	'They\'ll bend the knee or I\'ll destroy them. - Stannis Baratheon',
	'Get the keys and remove those chains from him, before you make me rue the day I raped your mother. - Roose Bolton',
	'Elia of Dorne.  I killed her screaming whelp.  Then I raped her.  Then I smashed her fucking head in like this. - Gregor Clegane',
	'Oberyn was ever the viper.  Deadly, dangerous, unpredictable.  No man dared tread on him.  I was the grass.  Pleasant, complaisant, sweet-smelling, swaying with every breeze.  Who fears to walk upon the grass?  But it is the grass that hides the viper from his enemies and shelters him until he strikes. - Doran Martell',
	'Old stories are like old friends, Old Nan used to say.  You have to visit them from time to time. - Bran Stark',
	'A good act does not wash out the bad, nor a bad act the good.  Each should have its own reward. - Stannis Baratheon',
	'Sometimes I think everyone is just pretending to be brave, and none of us really are.  Maybe pretending is how you get brave, I don\'t know. - Grenn',
	'By what right does the wolf judge the lion? - Jaime Lannister',
	'You want to rule?  This is what ruling is; lying on a bed of weeds, ripping them out by the root, one by one, before they strangle you in your sleep. - Cersei Lannister',
	'When you tear out a man\'s tongue, you are not proving him a liar, you\'re only telling the world that you fear what he might say. - Tyrion Lannister',
	'A Dothraki wedding without at least three deaths is considered a dull affair. - Illyrio Mopatis',
	'Words are like arrows, Arianne.  Once loosed, you cannot call them back. - Areo Hotah',
	'Robert could piss in a cup and men would call it wine, but I offer them cold clear water and they squint in suspicion and mutter to each other about how queer it tastes. - Stannis Baratheon',
	'If you think this has a happy ending, you haven\'t been paying attention. - Ramsay Bolton',
	'Do you remember that cave?  We should have stayed in that cave.  I told you so. - Ygritte',
	'"I never win anything.  The gods always smiled on Watt, though.  When the wildlings knocked him off the Bridge of Skulls, somehow he landed in a nice deep pool of water.  How lucky was that, missing all those rocks?"  "Was it a long fall?  Did landing in the pool of water save his life?"  "No.  He was dead already, from that axe in his head.  Stil, it was pretty lucky, missing the rocks." - Dolorous Edd and Grenn',
	'They pray to trees and golden idols and goat-headed abominations.  False gods... just so, and for that sin I kill them all.  I spill their blood upon the sea and sow their screaming women with my seed.  Their little gods cannot stop me, so plainly they are false gods.  I am more devout than even you, Aeron.  Perhaps it should be you who kneels to me for blessing. - Euron Greyjoy',
	'Who knows more of gods than I?  Horse gods and fire gods, gods made of gold with gemstone eyes, gods carved of cedar wood, gods chiseled into mountains, gods of empty air... I know them all.  I have seen their peoples garland them with flowers, and shed the blood of goats and bulls and children in their names.  And I have heard the prayers, in half a hundred tongues.  Cure my withered leg, make the maiden love me, grant me a healthy son.  Save me, succor me, make me walthy... protect me!  Protect me from mine enemies, protect me from the darkness, protect me from the crabs inside my belly, from the horselords, from the slavers, from the sellswords at my door.  Protect me from the Silence.  Godless?  Why, Aeron, I am the godliest man ever to raise sail!  You serve one god, Damphair, but I have served ten thousand.  From Ib to Asshai, when men see my sails, they pray. - Euron Greyjoy',
	'When I\'m king in my own right, I\'m going to outlaw beets. - Tommen Baratheon',
	'Until the Mountain crushed my brother\'s skull, no Dornishmen had died in this War of the Five Kings.  Tell me, Captain, is that my shame or my glory? - Doran Martell',
	'You grew up with actors.  You learned their craft and you learned it well.  I grew up with soldiers.  I learned how to die a long time ago. - Eddard Stark',
	'What men want does not matter.  Winter is almost upon us, boy.  And winter is death.  I would sooner my men die fighting for the Ned\'s little girl than alone and hungry in the snow, weeping tears that freeze upon their cheeks.  No one sings songs of men who die like that.  As for me, I am old.  This will be my last winter.  Let me bathe in Bolton blood before I die.  I want to feel it splatter across my face when my axe bites deep into a Bolton skull.  I want to lick it off my lips and die with the taste of it on my tongue. - Hugo Wull',
	'So many vows... they make you swear and swear.  Defend the king.  Obey the king.  Keep his secrets.  Do his bidding.  Your life for his.  But obey your father.  Love your sister.  Protect the innocent.  Defend the week.  Respect the gods.  Obey the laws.  It\'s too much.  No matter what you do, you\'re forsaking one vow for the other. - Jaime Lannister',
	'What is honor compared to a woman\'s love?  What is duty against the feel of a newborn son in your arms, or the memory of a brother\'s smile.  Wind and words.  Wind and words.  We are only human, and the gods have fashioned us for love.  That is our great glory and our great tragedy. - Aemon Targaryen',
	'There is no creature on earth half so terrifying as a truly just man. - Varys',
	'My real father died in King\'s Landing.  I made a choice, and I chose wrong. - Theon Greyjoy',
	'Never fear the darkness, Bran.  The strongest trees are rooted in the dark places of the earth.  Darkness will be your cloak, your shield, your mother\'s milk.  Darkness will make you strong. - Bloodraven',
	'If you die before you say her name, Ser, I will hunt you through the seven hells. - Oberyn Martell',
	'If a man does not use his member it grows smaller and smaller, until one day he wants to piss and cannot find it. - Tormund Giantsbane',
	'This is Stannis Baratheon.  The man will fight to the bitter end and then some. - Tywin Lannister',
	'Elia Martell, Princess of Dorne.  You raped her!  You murdered her!  You killed her children! - Oberyn Martell',
	'There are no men like me.  There\'s only me. - Jaime Lannister',
	'There are no true knights, no more than there are gods.  If you can\'t protect yourself, die and get out of the way of those who can.  Sharp steel and strong arms rule this world, don\'t ever believe any different. - Sandor Clegane',
	'Bring on your storm, my lord... and recall, if you do, the name of this castle. - Cortnay Penrose',
	'Lord Seaworth is a man of humble birth, but he reminded me of my duty, when all I could think of was my rights.  I had the cart before the horse, Davos said.  I was trying to win the throne to save the kingdom, when I should have been trying to save the kingdom to win the throne. - Stannis Baratheon',
	'Foes and false friends are all around me, Lord Davos.  They infest my city like roaches, and at night I feel them crawling over me.  My son Wendel came to the Twins as a guest.  He ate Lord Walder\'s bread and salt, and hung his sword upon the wall to feast with his friends.  And they murdered him.  Murdered, I say, and may the Freys choke upon their fables.  I drink with Jared, jape with Symond, promise Rhaegar the hand of my own beloved granddaughter... but never think that means I have forgotten.  The North remembers, Lord Davos.  The North remembers, and the mummer\'s farce is almost done.  My son is home. - Wyman Manderly.',
	'When dead men come hunting us in the night, do you think it matters who sits the Iron Throne? - Jeor Mormont',
	'It all goes back and back.  To our mothers and fathers and theirs before them.  We are puppets dancing on the strings of those who came before us, and one day our own children will take up our strings and dance in our steads. - Tyrion Lannister',
	'Can I dwell on what I scarce remember?  I held a castle on the Marches once, and there was a woman I was pledged to marry, but I could not find that castle today, nor tell you the color of that woman\'s hair.  Who knighted me, old friend?  What were my favorite foods?  It all fades.  Sometimes I think I was born on the bloody grass in that grove of ash, with the taste of fire in my mouth and a hole in my chest.  Are you my mother, Thoros? - Beric Dondarrion',
	'That\'s not a law, just a sword.  Happens I got one too. - Yoren of the Night\'s Watch',
	'The Drowned God gives every man a gift, even him; no man could piss longer or farther than Aeron Greyjoy, as he proved at every feast.  Once he bet his new longship against a herd of goats that he could quench a hearthfire with no more than his cock.  Aeron feasted on goat for a year, and named the longship Golden Storm, though Balon threatened to hang him from her mast when he heard what sort of ram his brother proposed to mount upon her prow. - Aeron Greyjoy',
	'I rose too high, loved too hard, dared too much. I tried to grasp a star, overreached, and fell. - Jon Connington',
	'I swear to you, I was never so alive as when I was winning this throne, or so dead as now that I\'ve won it. - Robert Baratheon',
	'Perhaps we can fly.  All of us.  How will we ever know unless we leap from some tall tower?  No man ever truly knows what he can do unless he dares to leap. - Euron Greyjoy',
	'I told you once, there are old sellswords and there are bold sellswords, but there are no old bold sellswords. - Brown Ben Plumm',
	'No tales were ever told of me.  Do you think I would be sitting here if it were otherwise?  Your amusements are your own, I will not chide you on that count, but you must be more discreet.  A peaceful land, a quiet people.  That has always been my rule.  Make it yours. - Roose Bolton',
	'Good men and true will fight for Joffrey, wrongly believing him the true king.  A northman might even say the same of Robb Stark.  But these lords who flocked to my brother\'s banners knew him for an usurper.  They turned their backs on their rightful king for no better reason than dreams of power and glory, and I have marked them for what they are.  Pardoned them, yes.  Forgiven, but not forgotten. - Stannis Baratheon',
	'I never asked for this, no more than I asked to be king.  Yet dare I disregard her?  We do not choose our destinies.  Yet we must... we must do our duty, no?  Great or small, we must do our duty. - Stannis Baratheon',
	'I never asked for this crown.  Gold is cold and heavy on the head, but so long as I am the king, I have a duty... if I must sacrifice one child to the flames to save a million from the dark... sacrifice... is never easy, Davos.  Or it is no true sacrifice. - Stannis Baratheon',
	'Robert was the true steel.  Stannis is pure iron, black and hard and strong, yes, but brittle, the way iron gets.  He\'ll break before he bends.  And Renly, that one, he\'s copper, bright and shiny, pretty to look at but not worth all that much at the end of the day. - Donal Noye',
	'Some battles are won with swords and spears, others with quills and ravens. - Tywin Lannister',
	'The greatest fools are ofttimes more clever than the men who laugh at them. - Tywin Lannister',
	'There is a tool for every task, and a task for every tool. - Tywin Lannister',
	'When your enemies defy you, you must serve them steel and fire.  When they go to their knees, however, you must help them back to their feet.  Elsewise no man will ever bend the knee to you.  And any man who must say "I am the king" is no true king at all.  Aerys never understood that, but you will.  When I\'ve won your war for you, we will restore the king\'s peace and the king\'s justice. - Tywin Lannister',
	'A ruler who hides behind paid executioners soon forgets what death is. - Eddard Stark',
	'Know the men who follow you and let them know you.  Don\'t ask your men to die for a stranger. - Eddard Stark',
	'I think it passing odd that I am loved by one for a kindness I never did, and reviled by so many for my finest act. - Jaime Lannister',
	'It was the white cloak that soiled me, not the other way around. - Jaime Lannister',
	'I learned form Ser Arthur Dayne, the Sword of the Morning, who could have slain all five of you with his left hand while he was taking a piss with the right. - Jaime Lannister',
	'I\'ve lost a hand, a father, a son, a sister, and a lover, and soon enough I will lose a brother.  And yet they keep telling me House Lannister has won this war. - Jaime Lannister',
	'Words are wind, and the only good wind is that which fills our sails. - Victarion Greyjoy',
	'A wolf is not a kraken.  What the kraken grasps it does not lose, be it longship or leviathan. - Victarion Greyjoy',
	'Asha Greyjoy did not intend to be taken alive.  She would die as she had lived, with an axe in her hand and a laugh upon her lips. - Asha Greyjoy',
	'I prefer my history dead.  Dead history is writ in ink, the living sort in blood. - Rodrik Harlaw',
	'Please.  A sword, that\'s all I ask.  Let me die as Theon, not as Reek. - Theon Greyjoy',
	'The Wall can stop an army, but not a man alone. - Mance Rayder',
	'Free folk don\'t follow names, or little cloth animals sewn on a tunic.  They won\'t dance for coins, they don\'t care how you style yourself or what that chain of office means or who your grandsire was.  They follow strength.  They follow the man. - Mance Rayder',
	'We all must choose.  Man or woman, young or old, lord or peasant, our choices are the same.  We choose light or we choose darkness. - Melisandre',
	'A hall to die in, and men to bury me.  I thank you, my lords... but I spit on your pity... I am a knight... I shall die a knight. - Barristan Selmy',
	'You are slow to learn, Lord Eddard.  Distrusting me was the wisest thing you\'ve don since you climbed down off your horse. - Petyr Baelish',
	'A bag of dragons buys a man\'s silence for a while, but a well-placed quarrel buys it forever. - Petyr Baelish',
	'Always keep your foes confused.  If they are never certain who you are or what you want, they cannot know what you are like to do next.  Sometimes the best way to baffle them is to make moves that have no purpose, or even seem to work against you.  Remember that, Sansa, when you come to play the game. - Petyr Baelish',
	'In King\'s Landing, there are two sorts of people.  The players and the pieces. - Petyr Baelish',
	'Everyone wants something, Alayne.  And when you know what a man wants you know who he is, and how to move him. - Petyr Baelish',
	'You could turn King\'s Landing upside down and not find a single man with a mockingbird sewn over his heart but that does not mean I am friendless. - Petyr Baelish',
	'Men of honor will do things for their children that they would never consider doing for themselves. - Petyr Baelish',
	'In the game of thrones, even the humblest pieces have wills of their own.  Sometimes they refuse to make the moves you\'ve planned for them.  Mark that well, Alayne.  It\'s a lesson that Cersei Lannister still has yet to learn. - Petyr Baelish',
	'I was wed three times and my wives gave me daughters.  Now only Beth remains to me.  My brother Martyn fathered four strong sons, yet only Jory lived to be a man.  When he was slain, Martyn\'s line died with him.  When we speak of the morrow nothing is ever certain. - Rodrik Cassel',
	'Love\'s not always wise, I\'ve learned.  It can lead us to great folly, but we follow our hearts... wherever they take us. - Robb Stark',
	'I have won every battle, yet somehow I\'m losing the war. - Robb Stark',
	'If you keep all your treasures in one purse, you only make it easier for those who would rob you. - Robb Stark',
	'We can only die.  Why else do we don these black cloaks, but to die in defense of the realm? - Qhorin Halfhand',
	'Why the oldest son, and not the best-fitted?  The crown will suit me, as it never suited Robert and would not suit Stannis. - Renly Baratheon',
	'The Red God has his due, sweet girl, and only death may pay for life.  This girl took three that were his.  This girl must give three in their places.  Speak the names, and a man will do the rest. - Jaqen H\'ghar',
	'Folly and desperation are ofttimes hard to tell apart. - Maester Luwin',
	'I can teach you history, healing, herblore.  I can teach you the speech of ravens, and how to build a castle, and the way a sailor steers his ship by the stars I can teach you to measure the days and marks the seasons, and at the Citadel in Oldtown they can teach you a thousand things more.  But, Bran, no man can teach you magic. - Maester Luwin',
	'A good lord comforts and protects the weak and helpless. - Maester Luwin',
	'The years pass in their hundreds and their thousands, and what does any man see of life but a few summers, a few winters? - Maester Luwin',
	'Ramsay.  Snow, my wife called me before she ate her fingers, but I say Bolton. - Ramsay Bolton',
	'Power tastes best when sweetened by courtesy; you had best learn that if you ever hope to rule. - Roose Bolton',
	'I have my own ghosts, Bran.  A brother that I loved, a brother that I hated, a woman I desired.  Through the trees, I see them still, but no word of mine has ever reached them.  The past remains the past.  We can learn from it, but we cannot change it. - Bloodraven',
	'All men are fools, if truth be told, but the ones in motley are more amusing than the ones with crowns. - Olenna Tyrell',
	'There is entirely too much tut-tutting in this realm, if you ask me.  All these kings would do a deal better if they put down their swords and listended to their mothers. - Olenna Tyrell',
	'Hush, Alerie, don\'t take that tone with me.  And don\'t call me mother.  If I\'d given birth to you, I\'m sure I\'d remember.  I\'m only to blame for your husband, the lord oaf of Highgarden. - Olenna Tyrell',
	'Have you seen Mace Tyrell\'s boy?  The Knight of Flowers, they call him.  Now there\'s a son any man would be proud to own to.  Last tourney, he dumped the Kingslayer on his golden rump, you ought to have seen the look on Cersei\'s face.  I laughed till my sides hurt. - Robert Baratheon',
	'It is R\'hllor who brings you back, my lord.  The Lord of Light.  I am only his instrument. - Thoros of Myr',
	'Spare me your empty little compliments, girl... and your ser\'s.  I am no knight.  I spit on them and their vows.  My brother is a knight. - Sandor Clegane',
	'The septons preach about the seven hells.  What do they know?  Only a man who\'s been burned knows what hell is truly like. - Sandor Clegane',
	'I like dogs better than knights... A hound will die for you, but never lie to you.  And he\'ll look you straight in the face. - Sandor Clegane',
	'What do you think a knight is for, girl?  You think it\'s all taking favors from ladies and looking fine in gold plate?  Knights are for killing.  I killed my first man at twelve.  I\'ve lost count of how many I\'ve killed since then.  High lords with old names, fat rich men dressed in velvet, knights puffed up like bladders with their honors, yes, and women and children too... they\'re all meat, and I\'m the butcher. - Sandor Clegane',
	'I could keep you safe.  They\'re all afraid of me.  No one would hurt you again, or I\'d kill them. - Sandor Clegane',	
	'I\'ve killed a lot more than him, I promise you.  You think that makes me some monster.  Well, maybe it does, but I saved your sister\'s life too.  The day the mob pulled her off her horse, I cut through them and brought her back to the castle, else she would have gotten what Lollys Stokeworth got.  And she sang for me.  You didn\'t know that, did you?  Your sister sang me a sweet little song. - Sandor Clegane',
	'Even brave men blind themselves sometimes, when they are afraid to see. - Beric Dondarrian',
	'The men of Westeros are ever rushing.  What good is this, I ask you?  He who hurries through life hurries to his grave. - Salladhor Saan',
	'Dragons old and young, true and false, bright and dark.  And you.  A small man with a big shadow, snarling in the midst of it all. - Moqorro',
	'I am the Greyjoy, Lord Reaper of Pyke, King of Salt and Rock, Son of the Sea Wind, and no man gives me a crown.  I pay the iron price.  I will take my crown, as Urron Redhand did five thousand years ago. - Balon Greyjoy',
	'Did Ned Stark dress you like that?  Was it his pleasure to garb you in velvets and silks and make you his own sweet daughter? - Balon Greyjoy',
	'No man has ever died from bending his knee.  He who kneels may rise again, blade in hand.  He who will not kneel stays dead, stiff legs and all. - Balon Greyjoy',
	'Young I was, and vain, but the sea washed my follies and my vanities away.  That man drowned, nephew.  His lungs filled with seawater, and the fish ate the scales off his eyes.  When I rose again, I saw clearly. - Aeron Greyjoy',
	'The god took me deep beneath the waves and drowned the worthless thing I was.  When he cast me forth again he gave me eyes to see, ears to hear, and a voice to spread his word, that I might be his prophet and teach his truth to those who have forgotten.  I was not made to sit upon the Seastone Chair... no more than Euron Crow\'s Eye.  For I have heard the god, who says, no godless man may sit my Seastone Chair. - Aeron Greyjoy',
	'I have my voice, and the god is with me.  Mine is the strength of the sea, a strength the Crow\'s Eye cannot hope to withstand.  The waves may break upon the mountain, yet still they come, wave upon wave, and in the end only pebbles remain where once the mountain stood.  And soon even the pebbles are swept away, to be ground beneath the sea for all eternity. - Aeron Greyjoy',
	'You ought to have no trouble catching our uncles.  One is drunk on seawater, after all, and the other is a great grey bullock so dim he\'ll probably get lost. - Asha Greyjoy',
	'Balon was mad, Aeron is madder, and Euron is maddest of them all. - Baelor Blacktyde',
	'The day is won, and yet you do not smile, boy.  The living should smile, for the dead cannot. - Dagmer Cleftjaw',
	'These old knights are more cunning than you think, or they would never have lived to see their first grey hair. - Dagmer Cleftjaw',
	'When treating with liars, even an honest man must lie. - Wyman Manderly',
	'The wolf will prove the boy is who we say he is, should the Dreadfort attempt to deny him.  That is my price, Lord Davos.  Smuggle me back my liege lord, and I will take Stannis Baratheon as my king. - Wyman Manderly',
	'The best pie you have ever tasted, my lords.  Wash it down with Arbor gold and savor every bite.  I know I shall. - Wyman Manderly',
	'Some dogs crawled atop me during the night.  My cloak was almost dry when one of them pissed in it.  Have you noticed that the rain stopped the instant I had a roof above me?  It will start again now that I\'m back out.  Gods and dogs alike delight to piss on me. - Dolorous Edd Tollett',
	'There are worse ways to die than warm and drunk.  I knew a brother drowned himself in wine once.  It was a poor vintage, though, and his corpse did not improve it. - Dolorous Edd Tollett',
	'I just want to say to whoever is voting for me that I would certainly make an awful Lord Commander.  But so would all these others. - Dolorous Edd Tollett',
	'My old septon used to say that books are dead men talking.  Dead men should keep quiet, is what I say.  No one wants to hear a dead man\'s yabber. - Dolorous Edd Tollett',
	'Place was overrun with rats when we moved in.  The spearwives killed the nasty buggers.  Now the place is overrun with spearwives.  There\'s days I want the rats back. - Dolorous Edd Tollett',
	'They say the king loved to hunt.  The things we love destroy us every time, lad.  Remember that. - Jeor Mormont',
	'Tarly, when I was a lad half your age, my lady mother told me that if I stood about with my mouth open, a weasel was like to mistake it for his lair and run down my throat.  If you have something to say, say it.  Otherwise, beware of weasels. - Jeor Mormont',
	'Now my bastards presume to teach me courtesy.  I\'ll speak any way I like, damn you.  I\'ve had three kings to guest in my life, and queens as well, do you think I require lessons from the likes of you, Ryger?  Your mother was milking goats the first time I gave her my seed. - Walder Frey',
	'Do you think I can\'t tell Lord Stannis from Lord Tywin?  They\'re both bungholes who think they\'re too noble to shit, but never mind about that, I know the difference. - Walder Frey',
	'Everyone was yelling stuff.  Hot Pie yelled hot pie.  He must have yelled it a hundred times. - Arya Stark',
	'In his chainmail shirt with a sword in his hand, Gendry looked almost a man grown, and dangerous.  Hot Pie looked like Hot Pie. - Arya Stark',
	'I have worked at the downfall of Tywin Lannister since the day they told me of Elia and her children. - Doran Martell',
	'Quentyn had never felt so much a boy as when he\'d stood before Daenerys Targaryen, pleading for her hand.  The thought of bedding her terrified him almost as much as her dragons had. - Quentyn Martell',
	'I let each man cut me once, before I kill him.  Count the cuts and you will know how many Strong Belwas has slain. - Strong Belwas',
	'A craven\'s knife can slay a queen as easily as a hero\'s. - Xaro Xhoan Daxos',
	'In this world, a man must learn to seize whatever gifts the gods chose to send him.  That was a lesson I learned at some cost. - The Tattered Prince',
	'Death, he knew, but slow.  I still have time.  A year.  Two years.  Five.  Some stone men live for ten.  Time enough to cross the sea, to see Griffin\'s Roost again.  To end the Usurper\'s line for good and all, and put Rhaegar\'s son upon the Iron Throne.  Then Lord Jon Connington could die content. - Jon Connington',
	'Aye, and from what I saw of Joffrey, you are as unfit a mother as you are a ruler. - Kevan Lannister',
	'My uncle Kevan would make a passably good regent if someone pressed the duty on him, but he will never reach for it.  The gods shaped him to be a follower, not a leader. - Tyrion Lannister',
	'Once, at the Citadel, I came into an empty room and saw an empty chair.  Yet I knew a woman had been there, only a moment before.  The cushion was dented where she\'d sat, the cloth was still warm, and her scent lingered in the air.  If we leave our smells behind us when we leave a room, surely something of our souls must remain when we leave this life?  The archmaesters did not like my thinking, though.  Well, Marwyn did, but he was the only one. - Qyburn',
	'The Citadel took my chain, but they could not take my knowledge. - Qyburn',
	'Once a horse is broken to the saddle, any man can mount him.  Once a beast\'s been joined to a man, any skinchanger can slip inside and ride him.  Orell was withering inside his feathers, so I took the eagle for my own.  But the joining works both ways, warg.  Orell lives inside me now, whispering how much he hates you.  And I can soar above the Wall, and see with eagle eyes. - Varamyr Sixskins',
	'I was a better smuggler than a knight, he had written to his wife, a better knight than a King\'s hand, a better King\'s hand than a husband.  I am so sorry Marya, I have loved you.  Please forgive the wrongs I did you. - Davos Seaworth',
	'Celtigar pronounced it admirable.  If I were to show him the contents of my privy he would pronounce that admirable as well. - Stannis Baratheon',
	'I\'ll have to take a page from Robert\'s book, not that he ever read one. - Stannis Baratheon',
	'They are children, Sansa thought.  They are silly little girls, even Elinor.  They\'ve never seen a battle, they\'ve never seen a man die, they know nothing.  Their dreams were full of songs and stories, the way hers had been before Joffrey cut her father\'s head off.  Sansa pitied them.  Sansa envied them. - Sansa Stark',
	'Perhaps magic was once a mighty force in the world, but no longer.  What little remains is no more than the wisp of smoke that lingers in the air after a great fire has burned out, and even that is fading.  Valyria was the last ember, and Valyria is gone. - Maester Luwin',
	'The Horned Lord once said that sorcery is a sword without a hilt.  There is no safe way to grasp it. - Dalla',
	'Some had been heroes, some weaklings, knaves, or cravens.  Most were only men, quicker and stronger than most, more skilled with sword and shield, but still prey to pride, ambition, lust, love, anger, jealousy, greed for gold, hunger for power, and all the other failings that afflicted lesser mortals.  The best of them overcame their flaws, did their duty, and died with their swords in their hands.  The worst... the worst were those who played the game of thrones. - Barristan Selmy',
	'I am IRONBORN!  I laugh at death. - Victarion Greyjoy',
	'Only Renly could vex me so with a piece of fruit.  He brought his doom on himself with his treason, but I did love him, Davos.  I know that now.  I swear, I will go to my grave thinking of my brother\'s peach. - Stannis Baratheon',
	'All you Westerosi make a shame of loving.  Ther is no shame in loving.  If your septons say there is, your seven gods must be demons.  In the isles we know better.  Our gods gave us legs to run with, noses to smell with, hands to touch and feel.  What mad cruel god would give a man eyes and tell him he must forever keep them shut, and never look at all the beauty in the world?  Only a monster god, a demon of the darkness. - Kojja Mo',
	'You wear your honor like a suit of armor, Stark.  You think it keeps you safe, but all it does is weigh you down and make it hard for you to move. - Petyr Baelish',
	'Help was not promised, lovely girl.  Only death. - Jaqen H\'ghar',
	'Bear Island knows no king save the King in the North, whose name is Stark. - Lyanna Mormont',
	'Death.  There will be death, aye.  Your lordship lost a son at the Red Wedding, I lost four upon the Blackwater.  And why?  Because the Lannisters stole the throne.  Go to King\'s Landing and look upon Tommen with your own eyes, if you doubt me.  A blind man could see it.  What does Stannis offer you?  Vengeance.  Vengeance for my sons and yours, for your husbands and your fathers and your brothers.  Vengeance for your murdered lord, your murdered king, your butchered princes.  Vengeance! - Davos Seaworth',
	'Your innocence may be as plain as the scar on your face, but it will not save you.  No more than your father will.  But I might.  Not as your judge.  As your champion. - Oberyn Martell',
	'See, lad, that\'s why he\'s the king and I\'m not.  I can outdrink, outfight, and outsing him, and my member\'s thrice the size o\' his, but Mance has cunning. - Tormund Giantsbane',
	'In the end, a gentle heart may be worth more than pride or valor. - Doran Martell',
	'Minds are like swords, I do fear.  The old ones go to rust. - Grand Maester Pycelle',
	'My order serves the realm, not the ruler.  Once I counseled King Aerys as loyally as I council King Robert now, so I bear this girl child of his no ill will.  Yet I ask you this, should war come again, how many soldiers will die?  How many towns will burn?  How many children will be ripped from their mothers to perish on the end of a spear?  Is it not wiser, even kinder, that Daenerys Targaryen should die now so that tens of thousands might live? - Grand Maester Pycelle',
	'Treason is a noxious weed.  It must be torn up, root and stem and seed, lest new traitors sprout from every roadside. - Grand Maester Pycelle',
	'My father won all the battles.  He killed Prince Rhaegar and took the crown, while your father was hiding under Casterly Rock.  A strong king acts boldly, he doesn\'t just talk. - Joffrey Baratheon',
	'We go home with an army, sweet sister.  With Khal Drogo\'s army, that is how we go home.  And if you must wed him and bed him for that, you will.  I\'d let his whole khalasar fuck you if need be, sweet sister, all forty thousand men, and their horses too if that was what it took to get my army. - Viserys Targaryen',
	'You were supposed to be my wife, to bear me children with silver hair and purple eyes, to keep the blood of the dragon pure.  I took care of you.  I taught you who you were.  I fed you.  I sold our mother\'s crown to keep you fed. - Viserys Targaryen',
	'No.  You were the betrayer.  You turned against me, against your own blood.  They cheated me.  Your horsey husband and his stinking savages.  They were cheats and liars.  They promised me a golden crown and gave me this. - Viserys Targaryen',
	'If you waste time trying to get people to love you, you\'ll end up the most popular dead man in town. - Bronn',
	'Though I would treasure your friendship, I\'m mainly interested in your facility with murder.  And if the day ever comes when you\'re tempted to sell me out, remember this; whatever their price, I\'ll beat it.  I like living. - Tyrion Lannister',
	'The bride weeps... dressing her in grey and white serves no good if the girl is left to sob.  The Freys might not care, but the northmen... they fear the Dreadfort, but they love the Starks.  Not me, but the rest, yes.  Old Whoresbane is only here because the Freys hold the Greatjon captive.  And do you imagine the Hornwood men have forgotten the Bastard\'s last marriage, and how his lady wife was left to starve, chewing her own fingers?  What do you think passes through their heads when they hear the new bride weeping?  Valiant Ned\'s precious little girl.  Lady Arya\'s sobs do us more harm than all of Lord Stannis\'s swords and spears. - Barbrey Dustin',
	'Lord Wyman is not the only one who lost kin at your Red Wedding, Frey.  Do you imagine Whoresbane loves you any better?  If you did not hold the Greatjon, he would pull out your entrails and make you eat them, as Lady Hornwood ate her fingers.  Flints, Cerwyns, Tallharts, Slates... they all had men with the Young Wolf.  The North remembers, Frey. - Barbrey Dustin',
	'If a song makes a maid want to slip off her clothes and feel the good warm sun kiss her skin, why is that the singer\'s fault? - Tom of Sevenstreams',
	'Knights?  Dondarrion\'s a knight, but the rest of you are the sorriest lot of outlaws and broken men I\'ve ever seen. - Sandor Clegane',
	'Once, she had loved Prince Joffrey with all her heart, and admired and trusted his mother, the queen.  They had repaid that love and trust with her father\'s head.  Sansa would never make that mistake again. - Sansa Stark',
	'My skin has gone from porcelain, to ivory, to steel. - Sansa Stark',
	'My son lies here broken and dying, Luwin, and you wish to discuss a new master of horse?  Do you think I care what happens in the stables?  Do you think it matters to me one whit?  I would gladly butcher every horse in Winterfell with my own hands if it would open Bran\'s eyes, do you understand that?  Do you? - Catelyn Stark',
	'Robb, if that sword could bring him back, I should never let you sheathe it until Ned stood at my side once more... but he is gone, and a hundred Whispering Woods will not change that. - Catelyn Stark',
	'You have courage.  Not battle courage perhaps but... I don\'t know... a kind of woman\'s courage. - Brienne of Tarth',
	'She don\'t speak.  You bloody bastards cut her throat too deep for that.  But she remembers. - Lem Lemoncloack',
	'What do a bunch o\' bloody peasants know about a lord\'s honor?  We know some about murder, though. - Lem Lemoncloak',
	'And there\'s this other band, led by this woman Stoneheart... Lord Beric\'s lover, according to one tale.  Supposedly she was hanged by the Freys, but Dondarrion kissed her and brought her back to life, and now she cannot die, no more than he. - Ser Hyle Hunt',
	'The Freys slashed her throat from ear to ear.  When we found her by the river she was three days dead.  Harwin begged me to give her the kiss of life, but it had been too long.  I would not do it, so Lord Beric put his lips to hers instead, and the flame of life passed from him to her.  And... she rose.  May the Lord of Light protect us.  She rose. - Thoros of Myr',
	'Winter will never come for the likes of us.  Should we die in battle, they will surely sing of us, and it\'s always summer in the songs.  In the songs all knights are gallant, all maids are beautiful, and the sun is always shining. - Brienne of Tarth',
	'Young or old, a true knight is sworn to protect those who are weaker than himself, or die in the attempt. - Brienne of Tarth',
	'I knew Brienne when she was no more than a girl playing at her father\'s feet in Evenfall Hall, and I knew her still better when the Evenstar sent her here to Storm\'s End.  She loved Renly Baratheon from the first moment she laid eyes on him, a blind man could see it. - Cortnay Penrose',
	'I asked him why he kept her close, if he thought her so grotesque.  He said that all his other knights wanted things of him, castles or honors or riches, but all that Brienne wanted was to die for him. - Loras Tyrell',
	'My lady, I have seen how you look at my brother.  Loras is valiant and handsome, and we all love him dearly... but your Imp will make a better husband.  He is a bigger man than he seems, I think. - Garlan Tyrell',
	'Robb Stark has won more battles in a year than the Lord of Highgarden had in twenty. - Tyrion Lannister',
	'I have never liked you, Cersei, but you were my own sister, so I never did you harm.  You\'ve ended that.  I will hurt you for this.  I don\'t know how yet, but give me time.  A day will come when you think yourself safe and happy, and suddenly your joy will turn to ashes in your mouth, and you\'ll know the debt is paid. - Tyrion Lannister',
	'Jaime, sweetling, I have known you since you were a babe at Joanna\'s breast.  You smile like Gerion and fight like Tyg and there\'s some of Keven in you, else you would not wear that cloak... but Tyrion is Tywin\'s son, not you.  I said that once to your father\'s face, and he would not speak to me for half a year. - Genna Lannister',
	'Jon was not afraid of death, but he did not want to die like that, trussed and bound and beheaded like a common brigand.  If he must perish, let it be with a sword in his hand, fighting his father\'s killers.  He was no true Stark, had never been one... but he could die like one.  Let them say that Eddard Stark had fathered four sons, not three. - Jon Snow',
	'There\'s no shame in fear, my father told me, what matters is how we face it. - Jon Snow',
	'The more you give a king, the more he wants.  We are walking on a bridge of ice with an abyss on either side.  Pleasing one king is difficult enough.  Pleasing two is hardly possible. - Jon Snow',
	'My lords, when Donal Noye was slain, it was this young man Jon Snow who took the Wall and held it, against all the fury of the north.  He has proved himself valiant, loyal, and resourceful.  Were it not for him, you would have found Mance Rayder sitting here when you arrived, Lord Slynt.  You are doing him a great wrong.  Jon Snow was Lord Mormont\'s own steward and squire.  He was chosen for that duty because the Lord Commander saw much promise in him.  As do I. - Maester Aemon',
	'Yes, it\'s you who ought to run, you and Lord Tywin and the Mountain and Ser Addam and Ser Amory and stupid Ser Lyonel whoever he is, all of you better run or my brother will kill you, he\'s a Stark, he\'s more wolf than man, and so am I. - Arya Stark',
	'Ah, Arya.  You have a wildness in you, child.  The \'wolf blood\', my father used to call it.  Lyanna had a touch of it, and my brother Brandon more than a touch.  It brought them both to an early grave.  Lyanna might have carried a sword, if my lord father had allowed it.  You remind me of her sometimes.  You even look like her. - Eddard Stark',
	'He\'d led me in war, hunted with a king, won honor in tourney melees, ridden with Brynden Blackfish and Greatjon Umber, fought in the Whispering Wood, bedded more girls than he could name, and yet his uncle was treating him as though he were still a child of ten. - Theon Greyjoy',
	'My daughter has taken an axe for a lover.  I will not have my son bedeck himself like a whore.  It is as I feared.  The green lands have made you soft, and the Starks have made you theirs. - Balon Greyjoy',
	'You\'re wrong.  Ned Stark was my gaoler, but my blood is still salt and iron. - Theon Greyjoy',
	'Only a fool humbles himself when the world is so full of men eager to do that job for him. - Theon Greyjoy',
	'Then perhaps Lord Eddard should have kept you chained to a dungeon wall.  Instead he raised you among his own sons, the sweet boys you have butchered, and to my undying shame I trained you in the arts of war.  Would that I had thrust a sword through your belly instead of placing one in your hand. - Rodrik Cassel',
	'I\'m not him, I\'m not the turncloak, he died at Winterfell.  My name is Reek.  It rhymes with freak. - Reek',
	'Theon found himself wondering if he should say a prayer.  Will the Old Gods hear me if I do?  They were not his gods, had never been his gods.  He was ironborn, a son of Pyke, his god was the Drowned God of the islands... but Winterfell was long leagues from the sea.  It had been a lifetime since any god had heard him.  He did not know who he was, or what he was, why he was still alive, why he had ever been born. - Theon Greyjoy',
	'Robb, who had been more a brother to Theon than any son born of Balon Greyjoy\'s loins.  Murdered at the Red Wedding, butchered by the Freys.  I should have been with him.  Where was I?  I should have died with him. - Theon Greyjoy',
	'She studied Theon Greyjoy\'s sly smile, wondering what it meant.  That young man had a way of looking as though he knew some secret jest that only he was privy to; Catelyn had never liked it. - Catelyn Stark',
	'You\'re Reek.  You\'ll always be Reek, no matter how sweet you smell.  Your nose may lie to you.  Remember your name.  Remember who you are. - Ramsay Bolton',
	'Strip off their skins.  Lord Bolton, he used to say a naked man has few secrets, but a flayed man\'s got none. - Ramsay Bolton',
	'Roose Bolton\'s cold and cunning, aye, but a man can deal with Roose.  We\'ve all known worse.  But this bastard son of his... they say he\'s mad and cruel, a monster. - Locke',
	'Was snow ever so black?  Ramsay took Lord Hornwood\'s lands by forcibly wedding his widow, then locked her in a tower and forgot her.  It is said she ate her own fingers in her extremity... and the Lannister notion of king\'s justice is to reward her killer with Ned Stark\'s little girl. - Wyman Manderly',
	'The Boltons have always been as cruel as they are cunning, but this one seems a beast in human skin. - Robett Glover',
	'Bulls are strong.  Bears.  I have seen my bastard fight.  He is not entirely to blame.  Reek was his tutor, the first Reek, and Reek was never trained at arms.  Ramsay is ferocious, I will grant you, but he swings that sword like a butcher hacking meat. - Roose Bolton',
	'His blood is bad.  He needs to be leeched.  The leeches suck away the bad blood, all the rage and pain.  No man can think so full of anger.  Ramsay, though... his tainted blood would poison even leeches, I fear. - Roose Bolton',
	'I count no day as lived unless I have loved a woman, slain a foeman, and eaten a fine meal. - Daario Naharis',
	'Better the butcher than the meat.  All kings are butchers.  Are queens so different? - Daario Naharis',
	'A queen must listen to all.  The highborn and the low, the strong and the weak, the noble and the venal.  One voice may speak you false, but in many there is always truth to be found. - Daenerys Targaryen',
	'It seems to me that a queen who trusts no one is as foolish as a queen who trusts everyone. - Daenerys Targaryen',
	'Do you know what it is like to be sold, squire?  I do.  My brother sold me to Khal Drogo for the promise of a golden crown.  Well, Drogo crowned him in gold, though not as he had wished, and I... my sun-and-stars made a queen of me, but if he had been a different man, it might have been much otherwise.  Do you think I have forgotten how it felt to be afraid? - Daenerys Targaryen',
	'Mother of dragons.  Mother of monsters.  What have I unleashed upon the world?  A queen I am, but my throne is made of burned bones, and it rests on quicksand.  Without dragons, how could she hope to hold Mereen, much less win back Westeros?  I am the blood of the dragon.  If they are monsters, so am I. - Daenerys Targaryen',
	'The frightened child who sheltered in my manse died on the Dothraki Sea, and was reborn in blood and fire.  This dragon queen who wears her name is a true Targaryen. - Illyrio Mopatis',
	'You are her perfect prince, agreed, bright and bold and comely as any maid could wish.  Daenerys Targaryen is no maid, however.  She is the widow of a Dothraki Khal, a mother of dragons and sacker of cities, Aegon the Conquereror with teats.  She may not prove as willing as you wish. - Tyrion Lannister',
	'Why should I go running to my aunt as if I were a beggar?  My claim is better than her own.  Let her come to me... in Westeros. - Aegon Targaryen',
	'The world is one great web, and no man dare not touch a single strand lest all the others tremble. - Illyrio Mopatis',
	'You Westerosi are all the same.  You sew some beast upon a scrap of silk, and suddenly you are all lions or dragons or eagles. - Illyrio Mopatis',
	'When the sun rises in the west and sets in the east.  When the seas go dry and mountains blow in the wind like leaves.  When your womb quickens again, and you bear a living child.  Then he will return, and not before. - Mirri Maz Duur',
	'To go north, you must go south.  To reach the west, you must go east.  To go forward you must go back, and to touch the light you must pass beneath the shadow. - Quaithe',
	'I dreamed of the man who came today, the one they call Reek.  You and your brother lay dead at his feet, and he was skinning off your faces with a long red blade. - Jojen Reed',
	'I pray for a glimpse of Azor Ahai, and R\'hllor shows me only Snow. - Melisandre',
	'Only their shadows, One most of all.  A tall and twisted thing with one black eye and ten long arms, sailing on a sea of blood. - Moqorro',
	'Fool\'s blood, king\'s blood, blood on the maiden\'s thigh, but chains for the guests and chains for the bridegroom, aye aye aye. - Patchface',
	'Who do you think killed all the dragons the last time around?  Gallant dragonslayers armed with swords?  The world the Citadel is building has no place in it for sorcery or prophecy or glass candles, much less for dragons.  Ask yourself why Aemon Targaryen was allowed to waste his life upon the Wall, when by rights he should have been raised to archmaester.  His blood was why.  He could not be trusted.  No more than I can. - Archmaester Marwyn',
	'They shall come day and night to see the wonder that has been born again into the world, and when they see they shall lust.  For dragons are fire made flesh, and fire is power. - Quaithe',
	'Khaleesi, better a man should swallow scorpions than trust in the spawn of shadows, who dare not show their face beneath the sun.  It is known. - Rakharo',
	'I have served six kings, but here before us lies the greatest man I ever knew.  Lord Tywin wore no crown, yet he was all a king should be. - Grand Maester Pycelle',
	'Men say Tywin never smiled, but he smiled when he wed your mother, and when Aerys made him Hand.  When Tarbeck Hall came crashing down on Lady Ellyn, that scheming bitch, Tyg claimed he smiled then, and he smiled at your birth, Jaime, I saw with my own eyes. - Genna Lannister',
	'Jaime and I are more than brother and sister.  We are one person in two bodies.  We shared a womb together.  He came into this world holding my foot, our old maester said.  When he is in me, I feel... whole. - Cersei Lannister',
	'A true man does what he will, not what he must. - Cersei Lannister',
	'Love is poison.  A sweet poison, yes, but it will kill you all the same. - Cersei Lannister',
	'The only way to keep your people loyal is to make certain they fear you more than they do the enemy. - Cersei Lannister',
	'I waited, and so can he.  I waited half my life.  She had played the dutiful daughter, the blushing bride, the pliant wife.  She had suffered Robert\'s drunken groping, Jaime\'s jealousy, Renly\'s mockery, Varys with his titters, Stannis endlessly grinding his teeth.  She had contended with Jon Arryn, Ned Stark, and her vile, treacherous, murderous dwarf brother, all the while promising herself that one day it would be her turn.  If Margaery Tyrell thinks to cheat me of my hour in the sun, she had bloody well think again. - Cersei Lannister',
	'I have sinned and must atone, must parade my shame before the eyes of every beggar in the city.  They think that this will break my pride, that it will make an end to me, but they are wrong. - Cersei Lannister',
	'Oh, Cersei is lovely to look at, truly, but cold... the way she guards her cunt, you\'d think she had all the gold of Casterly Rock between her legs. - Robert Baratheon',
	'The longer Cersei waits, the angrier she\'ll become, and anger makes her stupid.  I much prefer angry and stupid to composed and cunning. - Tyrion Lannister',
	'They are knights now, all three, and your sister has promised them further advancement.  And the eldest, Ser Osmund of the Kingsguard, dreams of certain other... favors... as well.  You can match the queen coin for coin, I have no doubt, but she has a second purse that is quite inexhaustible. - Varys',
	'Every man\'s a piece to start with, and every maid as well.  Even some who think they are players.  Cersei, for one.  She thinks herself sly, but in truth she is utterly predictable.  Her strength rests on her beauty, birth, and riches.  Only the first of those is truly her own, and it will soon desert her.  I pity her then.  She wants power, but has no notion what to do with it when she gets it. - Petyr Baelish',
	'It is not a question of wanting.  The throne is mine, as Robert\'s heir.  That is law.  After me, it must pass to my daughter, unless Selyse should finally give me a son.  I am king.  Wants do not enter into it.  I have a duty to my daughter.  To the realm.  Even to Robert.  He loved me but little, I know, yet he was my brother.  The Lannister woman gave him horns and made a motley fool of him.  She may have murdered him as well, as she murdered Jon Arryn and Ned Stark.  For such crimes there must be justice.  Starting with Cersei and her abominations.  But only starting.  I mean to scour that court clean.  As Robert should have done after the Trident. - Stannis Baratheon',
	'Demons made of snow and ice and cold.  The ancient enemy.  The only enemy that matters. - Stannis Baratheon',
	'Ned found it hard to imagine what could frighten Stannis Baratheon, who had once held Storm\'s End through a year of siege, surviving on rats and boot leather while the Lords Tyrell and Redwyne sat outside with their hosts, banqueting in sight of his walls. - Eddard Stark',
	'And Stannis has always felt he was cheated of Storm\'s End.  The ancestral seat of House Baratheon, his by rights... if you knew how many times he came to Robert singing that same dull song in that gloomy aggrieved tone he has.  When Robert gave the place to Renly, Stannis clenched his jaw so tight I thought his teeth would shatter. - Cersei Lannister',
	'Stannis Baratheon with a grievance was like a mastiff with a bone; he gnawed it down to splinters. - Jon Snow',
	'Is it your fault that Bronn\'s an insolent black-hearted rogue?  He\'s always been an insolent black-hearted rogue.  That\'s what I liked about him. - Tyrion Lannister',
	'Bronn was no knight, that was true.  Bronn was a battle-hardened killer. - Cersei Lannister',
	'She had seen Bronn fight on the high road; it was no accident that he had survived the journey while other men had died.  He moved like a panther, and that ugly sword of his seemed a part of his arm. - Catelyn Stark',
	'Have no fear, sers, your king is safe... no thanks to you.  Even know, I could cut through the five of you as easy as a dagger cuts cheese.  If you would serve under the Kingslayer, not a one of you is fit to wear the white.  Here, boy.  Melt it down and add it to the others, if you like.  It will do you more good than the swords in the hands of these five.  Perhaps Lord Stannis will chance to sit on it when he takes your throne. - Barristan Selmy',
	'Dismissing Selmy, where was the sense in that?  Yes, the man was old, but the name of Barristan the Bold still has meaning in the realm.  He lent honor to any man he served. - Tywin Lannister',
	'The Lion does not concern itself with the opinions of sheep. - Tywin Lannister',
	'I was weaned on venom, Dalt.  Any viper takes a bite of me will rue it. - Gerold Dayne',
	'Men call me Darkstar, and I am of the night. - Gerold Dayne',
	'There have always been men who found it easier to speak vows than to keep them. - Arys Oakheart',
	'I will not be remembered as Ser Arys the Unworthy.  I will not soil my cloak. - Arys Oakheart',
	'Serve, Obey, Protect.  Simple vows for a simple man. - Areo Hotah',
	'It is for my prince to command, for Hotah to obey. - Areo Hotah',
	'A man who sees nothing has no use for his eyes, cut them out and give them to your next outrider.  Tell him you hope that four eyes might see better than two... and if not, the man after him will have six. - Gregor Clegane',
	'I know the poison that my father used, and there is none slower or more agonizing.  Soon we may hear the Mountain screaming, even here in Sunspear. - Tyene Sand',
	'His size, Gregor is a very large man.  Also a very stupid one.  Too stupid to know when he should die, it seems. - Cersei Lannister',
	'She had made the mistake of speaking when Ser Gregor wanted quiet, so the Mountain had smashed her teeth to splinters with a mailed fist and broken her pretty little nose as well.  He would have done worse, no doubt, if Cersei had not called him down to King\'s Landing to face the Red Viper\'s spear.  Jaime would not mourn him. - Jaime Lannister',
	'If ever a man deserved to die screaming, it was Gregor Clegane. - Doran Martell',
	'Give me back my spear, Uncle.  Cersei sent us a head.  We should send her back a bag of them. - Obara Sand',
	'Nymeria was least dangerous when nearly naked.  Elsewise she was sure to have a dozen blades concealed about her person. - Areo Hotah',
	'Obara would make Oldtown our father\'s funeral pyre, but I am not so greedy.  Four lives will suffice for me.  Lord Tywin\'s golden twins, as payment for Elia\'s children.  The old lion, for Elia herself.  And last of all the little king, for my father... only royal blood can wash out my father\'s murder. - Nymeria Sand',
	'Oberyn wanted vengeance for Elia.  Now the three of you want vengeance for him.  I have four daughters, I remind you.  Your sisters.  My Elia is fourteen, almost a woman.  Obella is twelve, on the brink of maiden-hood.  They worship you, as Dorea and Loreza worship them.  If you should die, must El and Obella seek vengeance for you, then Dorea and Loree for them?  Is that how it goes, round and round forever?  I ask again, where does it end? - Ellaria Sand',
	'Secrets are worth more than silver or sapphires. - Varys',
	'The title was but a courtesy due him as a council member; Varys was lord of nothing but the spiderweb, the master of none but his whispers. - Catelyn Stark',
	'Lord Varys, sometimes I feel as though you are the best friend I have in King\'s Landing and sometimes I feel you are my worst enemy. - Tyrion Lannister',
	'Birds are lost, messages stolen or sold... there are things I might tell you of that eunuch that would chill your blood... - Grand Maester Pycelle',
	'You think you\'re the only one he whispers secrets to?  He gives each of us just enough to convince us that we\'d be helpless without him. - Cersei Lannister',
	'Small wonder that the Seven Kingdoms thought the free folk scarcely human.  They have no laws, no honor, not even simple decency.  They steal endlessly from each other, breed like beasts, prefer rape to marriage, and fill the world with baseborn children.  Yet he was growing fond of Tormund Giantsbane, great bag of wind and lies though he was. - Jon Snow',
	'Tormund Giantsbane seemed to me the sort of man who would make a good friend and a bad enemy, your Grace. - Jon Snow',
	'Might be you fooled these others, crow, but don\'t think you\'ll be fooling Mance.  He\'ll take one look a\' you and know you\'re false.  And when he does, I\'ll make a cloak o\' your wolf there, and open your soft boy\'s belly and sew a weasel up inside. - the Lord of Bones',
	'Rattleshirt, we called him.  Treacherous and bloodthirsty.  If there\'s honor in him, he hides it down beneath his suit of bones. - Jon Snow',
	'Qhorin was my enemy.  But also my brother, once.  So... shall I thank you for killing him, Jon Snow?  Or curse you? - Mance Rayder',
	'I will see, and hear, and learn, and when I have I will carry the word back to the Wall.  The wildlings had taken him for an oathbreaker, but in his heart he was still a man of the Night\'s Watch, doing the last duty that Qhorin Halfhand had laid on him.  Before I killed him. - Jon Snow',
	'Then hear me.  If we are taken, you will go over to them, as the wildling girl you captured once urged you.  They may demand that you cut your cloak to ribbons, that you swear them an oath on your father\'s grave, that you curse your brothers and your Lord Commander.  You must not balk, whatever is asked of you.  Do as they bid you... but in your heart, remember who and what you are.  Ride with them, eat with them, fight with them, for as long as it takes.  And watch. - Qhorin Halfhand',
	'The world was full of cravens who pretended to be heroes; it took a queer sort of courage to admit to cowardice as Samwell Tarly had. - Jon Snow',
	'I don\'t care if you\'re so scared you foul your breeches, and I don\'t care if a thousand wildlings are coming over the walls howling for your blood, you get those birds off, or I swear I\'ll hunt you through all seven hells and make you damn sorry that you didn\'t. - Jeor Mormont',
	'From this day forth, you will not call yourself a craven.  You\'ve faced more things this past year than most men face in a lifetime.  You can face the Citadel, but you\'ll face it as a Sworn Brother of the Night\'s Watch.  I can\'t command you to be brave, but I can command you to hide your fears. - Jon Snow',
	'The Night\'s Watch is a sworn brotherhood.  We have no families.  None of us will ever father sons.  Our wife is duty.  Our mistress is honor. - Benjen Stark',
	'His blood ran black.  Made him my brother as much as yours. - Yoren of the Night\'s Watch',
	'I got thirty this time, men and boys all bound for the Wall, and don\'t be thinking they\'re like that bastard brother o\' yours.  Lord Eddard gave me pick o\' the dungeons, and I didn\'t find no little lordlings down there.  This log, half o\' them would turn you over to the queen quick as spit for a pardon and maybe a few silvers.  The other half\'d do the same, only they\'d rape you first. - Yoren of the Night\'s Watch',
	'Brandon Stark was never shy about taking what he wanted.  I am old now, a dried-up thing, too long a widow, but I still remember the look of my maiden\'s blood on his cock the night he claimed me.  I think Brandon liked the sight as well.  A bloody sword is a beautiful thing, yes.  It hurt, but it was a sweet pain. - Barbrey Dustin',
	'Your lord father did not come to the wedding.  An insult, as I see it.  Even if he is dying.  He never came to my last wedding either.  He calls me the Late Lord Frey, you know.  Does he think I\'m dead?  I\'m not dead, and I promise you, I\'lll outlive him as I outlived his father.  Your family has always pissed on me, don\'t deny it, don\'t lie, you know it\'s true. - Walder Frey',
	'He would have killed me but for Howland Reed. - Eddard Stark',
	'My father knew the worth of Howland Reed. - Robb Stark',
	'No sword is strong until it\'s been tempered.  The Stark boy is a child.  No doubt he likes the sound of warhorns well enough, and the sight of his banners fluttering in the wind, but in the end it comes down to butcher\'s work.  I doubt he has the stomach for it. - Tywin Lannister',
	'My Lords!  Here is what I say to these two kings!  Renly Baratheon is nothing to me, nor Stannis neither.  Why should they rule over me and mine, from some flowery seat in Highgarden or Dorne?  What do they know of the Wall or the wolfswood or the barrows of the First Men?  Even their gods are wrong.  The Others take the Lannisters too, I\'ve had a bellyful of them.  Why shouldn\'t we rule ourselves again?  It was the dragons we married, and the dragons are all dead!  There sits the only king I mean to bow my knee to, m\'lords.  The King in the North! - Greatjon Umber',
	'Yes, Lord Umber, leave me to the king.  He means to give me a scolding before he forgives me.  That\'s how he deals with treason, our King in the North.  Or should I call you the King Who Lost the North, your Grace? - Rickard Karstark',
	'If you had to fall into a woman\'s arms, my son, why couldn\'t they have been Margaery Tyrell\'s? - Catelyn Stark',
	'Robb Stark won the war on the battlefield and lost it in a bedchamber. - Jaime Lannister',
	'More beast than boy, that one, puffed up with pride and bloodlust... Robb Stark betrayed us all.  He abandoned the north to the cruel mercies of the ironmen to carve out a fairer kingdom for himself along the Trident.  Then he abandoned the riverlords who had risked much and more for him, breaking his marriage pact with my grandfather to wed the first western wench who caught his eye.  The Young Wolf?  He was a vile dog and died like one. - Rhaegar Frey',
	'Grey Wind ate two of his fingers, and he laughed about it. - Robb Stark on Greatjon Umber',
	'Catelyn would sooner Lord Umber had seen fit to stay sober, but telling the Greatjon not to drink was like telling him not to breathe for a few hours. - Catelyn Stark',
	'Rickard Karstark killed more than a Frey and a Lannister.  He killed my honor. - Robb Stark',
	'My father never bellowed like the Greatjon, but he was no less dangerous in his wroth. - Alys Karstark',
	'Old gods or new, it makes no matter, no man is so accursed as the kinslayer. - Rickard Karstark',
	'The blood of the First Men flows in my veins as much as yours, boy.  You would do well to remember that.  I was named for your grandfather.  I raised my banners against King Aerys for your father, and against King Joffrey for you.  At Oxcross and the Whispering Wood and in the Battle of the Camps, I rode beside you, and I stood with Lord Eddard on the Trident.  We are kin, Stark and Karstark. - Rickard Karstark',
	'Any man who steps between a father and his vengeance asks for death. - Rickard Karstark',
	'Lord Balon\'s eldest brother had never given up the Old Way, even for a day.  His Silence, with its black sails and dark red hull, was infamous in every port from Ibben to Asshai, it was said. - Theon Greyjoy',
	'Euron Greyjoy is no man\'s notion of a king, if half of what Theon said of him was true. - Robb Stark',
	'Nuncle always had a fondness for freaks and fools.  My father used to fight with him about it.  Let the wizards call upon their gods.  The Damphair will call on ours, and drown them. - Asha Greyjoy',
	'The Crow\'s Eye brought back monsters from the east... aye, and wizards too. - Tristifer Botley',
	'Euron\'s gifts are poisoned. - Victarion Greyjoy',
	'Tell the Crow\'s Eye he\'s afraid of kinslaying and he\'ll murder one of his own sons just to prove you wrong. - Asha Greyjoy',
	'We are the ironborn, and once we were conquerors.  Our writ ran everywhere the sound of the waves was heard.  My brother would have been content with the cold and dismal north, my niece with even less... but I shall give you Lannisport.  Highgarden.  The Arbor.  Oldtown.  The Riverlands and the Reach, the Kingswood and the Rainwood, Dorne and the Marches, the Mountains of the Moon and the Vale of Arryn, Tarth and the Stepstones.  I say we take it all!  I say, we take Westeros. - Euron Greyjoy',
	'I am the storm, my lord, the first storm, and the last. - Euron Greyjoy',
	'Come with me to the House of the Undying, and you shall drink of truth and wisdom. - Pyat Pree',
	'When a maester donned his collar, he put aside the hope of children, yet Cressen had oft felt a father nontheless.  Robert, Stannis, Renly: three sons he had raised after the angry sea claimed Lord Steffon. - Maester Cressen',
	'The Old Gods stir and will not let me sleep.  I dreamt I saw a shadow with a burning heart butchering a golden stag, aye.  I dreamt of a man without a face, waiting on a bridge that swayed and swung.  On his shoulder perched a drowned crow with seaweed hanging from his wings.  I dreamt of a roaring river and a woman that was a fish.  Dead she drifted, with red tears on her cheeks, but when her eyes did open, oh, I woke from terror.  All this I dreamt, and more. - The Ghost of High Heart',
	'I dreamt a wolf howling in the rain, but no one heard his grief.  I dreamt such a clangor I thought my head myght burst, drums and horns and pipes and screams, but the saddest sound was the little bells.  I dreamt of a maid at a feast with purple serpents in her hair, venom dripping from their fangs.  And later I dreamt that maid again, slaying a savage giant in a castle built of snow. - The Ghost of High Heart',
	'Master Mott said Thoros could outdrink even King Robert.  They were pease in a pod, he told me, both gluttons and sots. - Gendry',
	'A grievous wound, aye, but Thoros healed it.  There\'s never been no better healer. - Lem Lemoncloak',
	'The gods be damned.  It was a hollow victory they gave me.  A crown... it was the girl I prayed them for.  Your sister, safe... and mine again, as she was meant to be.  I ask you, Ned, what good is it to wear a crown?  The gods mock the prayers of kings and cowherds alike. - Robert Baratheon',
	'Robert was never the same after he put on that crown.  Some men are like swords, made for fighting.  Hang them up and they go to rust. - Donal Noye',
	'Robert wanted smiles and cheers, always, so he went where he found them, to his friends and his whores.  Robert wanted to be loved.  My brother Tyrion has the same disease. - Cersei Lannister',
	'Robert... he is in my dreams as well.  Laughing.  Drinking.  Boasting.  Those were the things he was best at.  Those, and fighting.  I never bested him at anything. - Stannis Baratheon',
	'It\'s not Aerys I rue, it\'s Robert... Why is it no one names Robert oathbreaker?  He tore the realm apart, yet I am the one with shit for honor. - Jaime Lannister',
	'He climbed onto his throne over the corpses of children, though I will grant you he was no Joffrey. - Arianne Martell',
	'We all know what my brother would do.  Robert would gallop up to the gates of Winterfell alone, break them with his warhammer, and ride through the rubble to slay Roose Bolton with his left hand and the Bastard with his right.  I am no Robert.  But we will march, and we will free Winterfell... or die in the attempt. - Stannis Baratheon',
	'Ser Ryam Redwyne was the greatest knight of his day, and one of the worst Hands ever to serve a king.  Septon Murmison\'s prayers worked miracles, but as Hand he soon had the whole realm praying for his death.  Lord Butterwell was renowned for wit, Myles Smallwood for courage, Ser Otto Hightower for learning, yet they failed as hands, every one.  As for birth, the dragonkings oft chose Hands from amongst their own blood, with results as various as Baelor Breakspear and Maegor the Cruel.  Against this, you have Septon Barth, the blacksmith\'s son the Old King plucked from the Red Keep\'s library, who gave the realm forty years of peace and plenty.  Read your history, Lord Davos, and you will see that your doubts are groundless. - Maester Pylos',
	'Edric Storm, they call him.  He is said to be the very image of my brother.  If men were to see him, and then look again at Joffrey and Tommen, they could not help but wonder, I would think. - Stannis Baratheon',
	'Did the boy charm you?  He has that gift.  He got it from his father, with the blood.  He knows he is a king\'s son, but chooses to forget that he is bastard-born. - Stannis Baratheon',
	'Penrose chose to die rather than give him up.  It still angers me.  How could he think I would hurt the boy?  I chose Robert, did I not?  When that hard day came, I chose blood over honor. - Stannis Baratheon',
	'The Lord of Light cherishes the innocent.  There is no sacrifice more precious.  From his king\'s blood and his untainted fire, a dragon shall be born. - Melisandre',
	'A king\'s son, with the power of kingsblood in his veins.  Do you think you\'ve saved this boy, Onion Knight?  When the long night falls, Edric Storm shall die with the rest, wherever he is hidden.  Your own sons as well.  Darkness and cold will cover the earth.  You meddle in matters you do not understand. - Melisandre',
	'You have a passing clever father, Devan.  He makes me wish I had more smugglers in my service.  And fewer lords. - Stannis Baratheon',
	'I\'ve had shits that I\'ve liked better than Walder Frey. - Brynden Tully',
	'Red Rahloo means nothing here  You will only make the old gods angry.  They are watching from their island. - Hugo Wull',
	'Lord Pea Pod.  If you were a man, I would kill you for that, but my sword is made of too fine a steel to besmirch with craven\'s blood.  Aye, men are dying.  More will die before we see Winterfell.  What of it?  This is war.  Men die in war.  That is as it should be.  As it has always been. - Hugo Wull',
	'I know about the promiese... Maester Theomore, tell them!  A thousand years before the Conquest, a promise was made, and oaths were sworn in the Wolf\'s Den before the Old Gods and the new.  When we were sore beset and friendless, hounded from our homes and in peril of our lives, the wolves took us in and nourished us and protected us against our enemies.  The city is built upon the land they gave us.  In return we swore that we should always be their men.  Stark men! - Wylla Manderly',
	'Wylla.  Did you see how brave she was.  Even when I threatened to have her tongue out, she reminded me of the debt White Harbor owes to the Starks of Winterfell, a debt that can never be repaid.  Wylla spoke from the heart... not every woman can be as brave as my Wylla. - Wyman Manderly',
	'Past a certain point, all the dates grow hazy and confused, and the clarity of history becomes the fog of legend. - Hoster Blackwood',
	'Shagg, son of Dolf will chop off their manhoods and feed them to the crows. - Shagga, son of Dolf',
	'The Burned Men fear nothing.  Timett, son of Timett will ride with the lions. - Timett, son of Timett',
	'Kingthlayer... you are my captifth. - Vargo Hoat',
	'I buried an axe so deep into Willem\'s skull, they had to bury him with it. - Yoren of the Knight\'s Watch',
	'A man will tell you poison is dishonorable, but a woman\'s honor is different.  The Mother shaped us to protect our children, and our only dishonor is failure. - Lysa Arryn',
	'You must be blind as well as maimed, Ser.  Lift your eyes, and you will see the direwolf still flies above our walls. - Brynden Tully',
	'A godly man got no cause to fear such.  I said as much to that Mance Rayder once, when he come sniffing round.  He never listened, no more\'n you crows with your swords and your bloody fires.  That won\'t help you none when the white cold comes.  Only the gods will help you then.  You best get right with the gods. - Craster',
	'I dream of a tree sometimes.  A weirwood, like the one in the godswood.  It calls to me.  The wolf dreams are better.  I smell things, and sometimes I can taste the blood. - Bran Stark',
	'The stone is strong... the roots of the trees grow deep, and under the ground the Kings of Winter sit their thrones.  So long as those remained, Winterfell remained.  It was not dead, just broken.  Like me... I\'m not dead either. - Bran Stark',
	'All the tales agreed that the green men had strange magic powers.  Maybe they could help him walk again, even turn him into a knight.  They turned the little crannogman into a knight, even if it was only for a day, he thought.  A day would be enough. - Bran Stark',
	'No one had expected the broken boy to live.  The gods could not kill Bran, no more than I could.  It was a strange thought, and stranger still to remember that Bran might still be alive. - Theon Greyjoy',
	'They know.  The gods know.  They saw what I did.  And for one strange moment it seemed as if it were Bran\'s face carved into the pale trunk of the weirwood, staring down at him with eyes red and wise and sad.  Bran\'s ghost, he thought, but that was madness.  Why should Bran want to haunt him?  He had been fond of the boy, had never done him any harm.  It was not Bran we killed.  It was not Rickon.  They were only miller\'s sons, from the mill by the Acorn Water. - Theon Greyjoy',
	'A face took shape within the hearth.  Stannis?  she thought, for just a moment... but no, these were not his features.  A wooden face, corpse white.  Was this the enemy?  A thousand red eyes floated in the rising flames.  He sees me.  Beside him, a boy with a wolf\'s face threw back his head and howled. - Melisandre',
	'Most of him has gone into the tree... he has lived beyond his mortal span, and yet he lingers.  For us, for you, for the realms of men.  Only a little strength remains in his flesh.  He has a thousand eyes and one, but there is much to watch.  One day you will know. - Leaf',
	'How many eyes does Lord Bloodraven have?  the riddle ran.  A thousand eyes, and one.  Some claimed the King\'s Hand was a student of the dark arts who could change his face, put on the likeness of a one-eyed dog, even turn into a mist.  Packs of gaunt gray wolves hunted down his foes, men said, and carrion crows spied for him and whispered secrets in his ear.  Most of the tales were only tales, Dunk did not doubt, but no one could doubt that Bloodraven had informers everywhere. - Duncan the Tall',
	'I have been called many things, my lord, byt kind is seldom one of them. - Maester Aemon',
	'Jon, did you ever wonder why the men of the Night\'s Watch take no wives and father no children?  So they will not love, for love is the bane of honor, the death of duty. - Maester Aemon',
	'Knowledge is a weapon, Jon.  Arm yourself well before you ride forth to battle. - Maester Aemon',
	'He was a good man... no.  He was a great man.  A maester of the Citadel, chained and sworn, and Sworn Brother of the Night\'s Watch, ever faithful.  When he was born they named him for a hero who had died too young, but though he lived a long time, his own life was no less heroic.  No man was wiser, or gentler, or kinder.  At the Wall, a dozen lords commander came and went during his years of service, but he was always there to counsel them.  He counseled kings as well.  He could have been a king himself, but when they offered him the crown he told them they should give it to his younger brother.  How many men would do that?  He was the blood of the dragon, but now his fire has gone out.  He was Aemon Targaryen.  And now his watch is ended. - Samwell Tarly',
	'Many good men have been bad kings, and some bad men have been good kings. - Maester Aemon',
	'The children are gone from the world, and their wisdom with them.  It had to do with the faces in the trees, we think.  The First Men believed that the greenseers could see through the eyes of the weirwoods.  That was why they cut down the trees whenever they warred upon the children.  Supposedly the greenseers also had the power over the beasts of the wood and the birds in the trees.  Even fish. - Maester Luwin',
	'No, only a boy who dreams.  The greenseers were more than that.  They were wargs as well, as you are, and the greatest of them could wear the skins of any beast that flies or swims or crawls, and could look through the eyes of the weirwoods as well, and see the truth that lies beneath the world. - Jojen Reed',
	'A thousand eyes, a hundred skins, wisdom deep as the roots of ancient trees.  Greenseers. - Bloodraven',
	'The Old Gods have no power in the south.  The weirwoods there were all cut down, thousands of years ago. - Osha',
	'The singers of the forest had no books.  No ink, no parchment, no written language.  Instead they had the trees, and the weirwoods above all.  When they died, they went into the wood, into leaf and limb and root, and the trees remembered.  All their songs and spells, their histories and prayers, everything they knew about this world.  Maesters will tell you that the weirwoods are sacred to the old gods.  The singers believe they are the old gods.  When singers die they become part of that godhood. - Jojen Reed',
	'Time is different for a tree than for a man.  Sun and soil and water, these are the things a weirwood understands, not days and years and centuries.  For men, time is a river.  We are trapped in its flow, hurtling from past to present, always in the same direction.  The lives of trees are different.  They root and grow and die in one place, and that river does not move them.  The oak is the acorn, the acorn is the oak.  And the weirwood... a thousand human years are a moment to a weirwood, and through such gates you and I may gaze into the past. - Bloodraven',


]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}

